import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { images } from "@/assets/img/image";
import Logo from "@/assets/img/logo.png";
import { Toaster } from "@/components/ui/toaster";
import GradientBackground from "@/components/gradient-bg";
const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Fajar Raihan | Web Developer",
  description: "Generated by create next app",
  icons: Logo,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <GradientBackground />
        <main className="w-11/12 mx-auto">
          <Header />
          {children}
          <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
